const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let apiKey=localStorage.getItem('nzbharbor_api_key')||'';let cfg=null;let jobs=[];
function headers(json=false){const h={};if(apiKey)h['X-Api-Key']=apiKey;if(json)h['Content-Type']='application/json';return h}
function tell(msg,error=false){const n=$('#notice');n.textContent=msg;n.className='notice'+(error?' error':'');clearTimeout(tell.t);tell.t=setTimeout(()=>n.classList.add('hidden'),6500)}
async function req(url,opt={}){opt.headers={...headers(),...(opt.headers||{})};const r=await fetch(url,opt);if(r.status===401){throw new Error('API key required or incorrect. Read it from ./config/config.json and use “Set API key”.')}if(!r.ok){throw new Error((await r.text())||`HTTP ${r.status}`)}const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
function ensureKey(){if(apiKey)return true;const k=prompt('Enter NZBHarbor API key. You can find it in ./config/config.json');if(!k)return false;apiKey=k.trim();localStorage.setItem('nzbharbor_api_key',apiKey);return true}
async function bootstrap(){if(!ensureKey()){tell('API key is required to manage NZBHarbor.',true);return}await refresh();setInterval(()=>refresh(false),3000)}
async function refresh(showErrors=true){try{[jobs,cfg]=await Promise.all([req('/api/v1/jobs'),req('/api/v1/config')]);render()}catch(e){if(showErrors)tell(e.message,true)}}
function render(){const q=jobs.filter(j=>!['completed','failed'].includes(j.status)),done=jobs.filter(j=>j.status==='completed'),failed=jobs.filter(j=>j.status==='failed');$('#statQueue').textContent=q.length;$('#statDone').textContent=done.length;$('#statFailed').textContent=failed.length;$('#statServers').textContent=cfg?.servers?.length||0;renderJobs('#activeJobs',q.filter(j=>['downloading','post-processing'].includes(j.status)));renderJobs('#queueJobs',q);renderJobs('#historyJobs',jobs.filter(j=>['completed','failed'].includes(j.status)));if(cfg){$('#apiKey').value=cfg.api_key||'';renderServers()}}
function size(n=0){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;if(n<1073741824)return `${(n/1048576).toFixed(1)} MB`;return `${(n/1073741824).toFixed(2)} GB`}
function speed(n=0){return n?`${size(n)}/s`:'—'}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderJobs(sel,list){const el=$(sel);if(!list.length){el.innerHTML='<div class="empty">Nothing here yet.</div>';return}el.innerHTML=list.map(j=>`<div class="job"><div class="jobname"><b title="${esc(j.name)}">${esc(j.name)}</b><small>${esc(j.category)} • ${size(j.total_bytes)}</small></div><div><span class="status ${esc(j.status)}">${esc(j.status)}</span><div class="jobmeta">${speed(j.speed)}</div></div><div><div class="jobmeta">${Number(j.progress||0).toFixed(1)}%</div><div class="progress"><i style="width:${Math.min(100,Math.max(0,j.progress||0))}%"></i></div>${j.error?`<div class="jobmeta" title="${esc(j.error)}">${esc(j.error)}</div>`:''}</div><div class="actions">${j.status==='paused'?`<button onclick="jobAction('${j.id}','resume')">Resume</button>`:(!['completed','failed'].includes(j.status)?`<button onclick="jobAction('${j.id}','pause')">Pause</button>`:'')}${j.status==='failed'?`<button onclick="jobAction('${j.id}','resume')">Retry</button>`:''}<button onclick="jobAction('${j.id}','delete')">Delete</button></div></div>`).join('')}
async function jobAction(id,action){if(action==='delete'&&!confirm('Remove this job from NZBHarbor?'))return;try{await req(`/api/v1/jobs/${id}/${action}`,{method:'POST'});await refresh()}catch(e){tell(e.message,true)}}
function modal(show){$('#modal').classList.toggle('show',show)}
$('#addBtn').onclick=()=>modal(true);$('#modal').onclick=e=>{if(e.target.id==='modal')modal(false)};
$('#uploadForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);$('#uploadMsg').textContent='Adding…';try{await req('/api/v1/jobs',{method:'POST',body:fd});e.target.reset();$('#uploadMsg').textContent='Added to queue.';setTimeout(()=>modal(false),500);await refresh()}catch(err){$('#uploadMsg').textContent=err.message}};
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');$('#title').textContent=b.textContent;$('#subtitle').textContent=b.dataset.view==='servers'?'Provider configuration and API credentials.':'NZBHarbor • Docker-first Usenet downloader';if(b.dataset.view==='servers'&&cfg)renderServers()});
function serverTemplate(s={},i){return `<div class="server" data-i="${i}"><label>Name<input data-k="name" value="${esc(s.name||'')}" placeholder="Primary"></label><label>Host<input data-k="host" value="${esc(s.host||'')}" placeholder="news.example.com"></label><label>Port<input data-k="port" type="number" value="${s.port||563}"></label><label class="checkbox"><input data-k="tls" type="checkbox" ${s.tls!==false?'checked':''}>TLS</label><label>User<input data-k="username" value="${esc(s.username||'')}"></label><label>Password<input data-k="password" type="password" value="${esc(s.password||'')}"></label><label>Priority<input data-k="priority" type="number" value="${s.priority??0}"></label><label class="checkbox"><input data-k="enabled" type="checkbox" ${s.enabled!==false?'checked':''}>On</label><div class="actions"><button onclick="testServer(${i})">Test</button><button onclick="removeServer(${i})">×</button></div></div>`}
function renderServers(){if(!cfg)return;$('#serverRows').innerHTML=(cfg.servers||[]).map(serverTemplate).join('')||'<div class="empty">No Usenet provider configured.</div>'}
function pullServers(){return $$('#serverRows .server').map(row=>{const v=k=>row.querySelector(`[data-k="${k}"]`);return{name:v('name').value.trim(),host:v('host').value.trim(),port:Number(v('port').value)||563,tls:v('tls').checked,username:v('username').value.trim(),password:v('password').value,connections:4,priority:Number(v('priority').value)||0,enabled:v('enabled').checked}})}
function addServer(){cfg.servers=pullServers();cfg.servers.push({name:'',host:'',port:563,tls:true,username:'',password:'',connections:4,priority:cfg.servers.length,enabled:true});renderServers()}
function removeServer(i){cfg.servers=pullServers();cfg.servers.splice(i,1);renderServers()}
async function saveServers(){try{cfg.servers=pullServers();await req('/api/v1/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});tell('Configuration saved.');await refresh()}catch(e){tell(e.message,true)}}
async function testServer(i){try{const servers=pullServers(),result=await req('/api/v1/test-server',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(servers[i])});tell(result.ok?result.message:(result.error||'Connection failed'),!result.ok)}catch(e){tell(e.message,true)}}
async function copyKey(){try{await navigator.clipboard.writeText($('#apiKey').value);tell('API key copied.')}catch{tell('Could not copy API key.',true)}}
window.refresh=refresh;window.jobAction=jobAction;window.modal=modal;window.addServer=addServer;window.removeServer=removeServer;window.saveServers=saveServers;window.testServer=testServer;window.copyKey=copyKey;
bootstrap();
